.gitignore, .sequelizerc, db/config/config.example.js, db/migrations/20200922125001-create-users.js, db/migrations/20200922125225-create-builds.js, db/models/builds.js, db/models/index.js, db/models/users.js, db/seeders/20200922125006-users.js, db/seeders/20200922125247-builds.js, db/seeders/bp1.json, db/seeders/bp2.json, package.json, yarn.lock
- This commit adds the initial data model and the dependencies for Sequelize as the ORM for factorio-builds.
- Currently there is no integration into the next.js app, only the model definitions
- No change has been made to existing models, as such this is completely unrelated to current resources
To bootstrap the datasource, make sure you have the sequelize command line installed with `yarn global add sequelize-cli`. Then you'll need to use the `db/config/config.example.js` and create `db/config/config.js` with your database credentials.
To create the data models run `sequelize db:migrate` and to populate use `sequelize db:seed:all`
=> Adding initial data model and Sequelize ORM

components/BuildPage/build-page.component.tsx, utils/blueprint.ts
shows the count of items in a blueprint in the build page, if it's not a book
=> feat: show items per blueprint

components/BuildPage/build-page.component.tsx, components/Header/header.component.tsx, components/ListItemBuild.tsx, db/models/build.js, pages/api/build/index.ts, pages/build/[id].tsx, pages/build/create.tsx, pages/build/index.tsx, pages/index.tsx, types/index.ts
I'm attempting a few things in this WIP PR:
1) Cleaning up the Sequelize models; as I get a bit more familiar with the convention realizing there are some fields that we don't need to explicitly define
2) Removing calls to the api from the `getServerStaticProps` in lieu of directly connecting to the database
3) Cleaning up the `IBuild` interface with `IMetadata` and correct types for the keys in the map.
Currently however this doesn't work when viewing a build page. The index page works, but did require a hack with the JSON DateTime as documented in https://github.com/vercel/next.js/discussions/11209#discussioncomment-35915
The build page is totally broken, and I have no idea why:
```
SerializableError: Error serializing `.meta` returned from `getServerSideProps` in "/build/[id]".
Reason: …
```
=> Remove API Fetch calls from model pages

pages/api/build/index.ts, pages/build/create.tsx
I don't know why but the `tileable` checkbox is disabled. Otherwise this creates a record with markdown description.
p.s. the user is hard-coded for now.
=> Adding a description field to create model

pages/build/create.tsx
Make "tileable" checkable, remove warnings on mapped elements missing a `key`, and invalid `null` property on select.
=> fix create form

.env.example, pages-components/BuildFormPage/build-form-page.component.tsx
We had inconsistent usage of `APP_URL` and `APP_ENDPOINT`. This change updates the code to use `APP_URL` exclusively and updates the example to match.
- Fixes #199
=> Standardize env variable on APP_URL

components/ui/Button/button.component.tsx, components/ui/Button/button.styles.tsx, icons/copy.tsx, pages-components/BuildPage/build-page.component.tsx, pages-components/BuildPage/build-page.styles.tsx
- Adds tileable and marked inputs to blueprint page
- Tweak build body formatting
- Make the cursor a pointer on highlighting "expand blueprint"
- Adds a copy (blueprint string) to clipboard button
=> feat: increment build page

components/ui/BuildCardList/build-card-list.component.tsx, db/seeds/data/builds.ts, pages/index.tsx, server/usecase/build.usecase.ts, types/index.ts
This changes adds `isBook` as a boolean on IMetadata interface. This is easier to do at creation time so we don't need to decode the blueprint for the index page, which will be done in a following contribution.
- Fixes #201
=> Add isBook to IMetadata interface

pages/index.tsx
The removes the blueprint from the query, which is not needed on the index page.
Fixes #185
=> Adding a lighter weight index page query

frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/pager.component.tsx, frontend/components/pages/BuildFormPage/step-1.component.tsx, frontend/components/pages/BuildFormPage/step-2-cover.component.tsx, frontend/components/pages/BuildFormPage/step-2-image.component.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx
This moves the flow to a 3 step flow that's necessary for blueprint books.
Book flow still to do in a follow-up PR.
=> feat: handle flow for a single blueprint cover

backend/src/FactorioTech.Api/Controllers/PayloadController.cs, backend/src/FactorioTech.Api/Services/LinkBuilder.cs, backend/src/FactorioTech.Api/ViewModels/PayloadModel.cs, backend/src/FactorioTech.Api/ViewModels/ViewModelBase.cs, backend/src/FactorioTech.Core/IdentityExtensions.cs, backend/src/FactorioTech.Core/Services/ImageService.cs, frontend/types/generated-api.ts
@veksen ideally you could add a button/icon to delete renderings at some point. for now I'm just using this API to delete dodgy renderings manually
=> add `DELETE {hash}/rendering`

frontend/components/ui/Header/header.component.tsx, frontend/components/ui/UserDropdown/user-dropdown.component.tsx
- Hides the add build button on mobile (it doesn't make much sense in the first place, how do you get your blueprint string?)
- Hides the username as it simply doesn't fit
=> ui: improve responsiveness on header

frontend/components/pages/BuildPage/build-page.styles.tsx, frontend/components/pages/BuildPage/tabs/blueprints-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx, frontend/components/ui/BuildHeader/build-header.component.tsx
Moves the (invalid) "View in blueprint" button to blueprint items, for books.
=> feat: move view in editor button for books

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-cover.component.tsx, frontend/components/pages/BuildPage/tabs/blueprints-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx, frontend/components/ui/BlueprintItemExplorer/blueprint-item-explorer.component.tsx, frontend/components/ui/BlueprintItemExplorer/blueprint-item-explorer.provider.tsx, frontend/components/ui/BlueprintItemExplorer/index.ts
Contains a few bugfixes and QoL on blueprint items:
- Previously, only the first level of items would show a "select render" button
- The "expand" would collapse given a long-ish title
- The indentation across multiple levels was wrong
- Remove the "raw", "view in editor", and "copy to clipboard" buttons when creating a blueprint
Notably, was forced to encapsulate rendering of the blueprint items into a new component providing context to items via the Context API.
closes #534
=> fix: normalize blueprint item behavior across context

frontend/components/ui/ItemIcon/item-icon.component.tsx, frontend/components/ui/WithIcons/__tests__/__snapshots__/with-icons.test.tsx.snap, frontend/components/ui/WithIcons/__tests__/useParseRichText.test.ts, frontend/components/ui/WithIcons/__tests__/with-icons.test.tsx, frontend/components/ui/WithIcons/useParseRichText.hook.ts, frontend/components/ui/WithIcons/with-icons.component.tsx, frontend/jest.config.js, frontend/jest.setup.js, frontend/package.json, frontend/yarn.lock
This switches to a more flexible parsing of the Factorio rich text, including tests, to make it easier to iterate over.
The idea is to support #532 and #531, and possibly more in the future.
There are probably better ways to build a parser, so open to a refactor.
=> refact: switch to rich text parsing

frontend/components/pages/BuildFormPage/step-1.component.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx, frontend/utils/blueprint-heuristics.ts
1. Avoid showing counter without a selection (seeing a bunch of 0s was just more confusing), this aligns with the UX in the tags filtering on the main page.
2. Fix the incorrect number for blueprint books.
=> feat(build form): improve tags selection counter

frontend/types/index.ts, frontend/utils/blueprint-heuristics.ts
Trying to access `blueprint.type` would crash the form.
=> fix: blueprint and books don't have a type

frontend/components/pages/BuildFormPage/build-form-page.helpers.ts
I believe this is the correct behavior, which solves this error:
=> fix: prevent sending hash and file

frontend/components/ui/BuildCard/build-card.component.tsx
This will load 300px/600px retina images on the homepage to lighten the load.
300px is dummy for now, while somewhat accurate, another PR is coming to load the correct size, responsively.
Before:
First Contentful Paint 0.4 s
Time to Interactive 0.8 s
Speed Index 1.3 s
Largest Contentful Paint 2.4 s
=> perf: optimize homepage images to be max 300px

frontend/components/ui/WithIcons/__tests__/useParseRichText.test.ts, frontend/components/ui/WithIcons/useParseRichText.hook.ts, frontend/components/ui/WithIcons/with-icons.component.tsx
First implementation to parse the color in rich text, closes #531
=> feat: parse color in rich text

frontend/components/ui/Dropdown/dropdown.component.tsx
https://github.com/adobe/react-spectrum/pull/1239 was merged, so this can be removed.
=> refact: use TreeProps from react-aria as it is now exported

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/tabs/image-mobile-tab.component.tsx, frontend/components/ui/BuildCard/build-card.component.tsx, frontend/components/ui/BuildImage/build-image.component.tsx, frontend/components/ui/BuildImage/index.ts, frontend/components/ui/BuildList/build-list.component.tsx
First step to use the optimized images everywhere that was using `next/image`, plus extracting it to its own component.
=> perf: optimize images

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/tabs/image-mobile-tab.component.tsx, frontend/components/ui/BuildCard/build-card.component.tsx, frontend/components/ui/BuildImage/build-image.component.tsx, frontend/components/ui/BuildImage/build-image.styles.tsx, frontend/components/ui/BuildList/build-list.component.tsx
This moves away from `next/image`, as it can only handle responsive images as per the viewport width, and not the current context the image resides in.
=> perf: move away from next/image, in-house responsive loading image within context

frontend/components/form/Checkbox/checkbox.styles.tsx, frontend/components/form/Input/input.component.tsx, frontend/components/form/Radio/radio.styles.tsx
The input wasn't getting focused properly when wrapped in a sub-component, and the checkbox/radio weren't visually focused.
=> fix(a11y): improve inputs focus

frontend/components/ui/BuildImage/build-image.component.tsx
the hook was loading the full-size cover, while the image was using a compressed cover, causing both to be downloaded.
=> perf: avoid loading full size image cover
