db/models/builds.js, db/models/index.js, db/models/users.js, pages/api/builds/index.ts
Some small cleanup to get the models working. Also stopped returning the blueprint and json in the query.
=> Fixing js models and narrowing query response

pages/api/builds/index.ts, pages/builds/create.tsx
This makes it possible to save a build. I had to build a uuid on save, but I think that should be part of the schema. Also not certain on the direction for metadata, so saving some dummy, as well as only the first category.
=> feat: save build to database

components/BuildCard/build-card.component.tsx, components/BuildCard/build-card.styles.tsx, components/BuildCardList/build-card-list.component.tsx, components/ListDetailBuild.tsx, package.json, pages/api/builds/[id].ts, pages/builds/[id].tsx
I don't consider this _good enough_ for resolving #27 but it's a good start.
=> Adding build page

pages/api/builds/[id].ts, pages/api/builds/index.ts, pages/builds/[id].tsx, pages/builds/index.tsx, pages/index.tsx, pages/users/[id].tsx, pages/users/index.tsx, redux/store.ts
Switch from SSG to SSR as it's more appropriate to us, and resolve the errors preventing the build.
=> switch to ssr

components/BuildPage/build-page.component.tsx, components/BuildPage/build-page.styles.tsx, package.json, types/index.ts, utils/blueprint.ts, utils/mock-builds-data.ts, yarn.lock
This gives us the bootstrap code to start doing manipulation with the blueprint data, plus add the JSON string as part of the page, if we want to see it.
=> feat: decode blueprint data

components/BuildPage/build-page.component.tsx
=> Format json output for build page

components/BuildPage/build-page.component.tsx, db/migrations/20200922125225-create-builds.js, db/models/build.js, db/seeders/20200922125247-builds.js, db/seeders/bp3.json, types/index.ts
This PR Adds a description to the schema and displays it on the build page.
Still to do (and not in scope):
- Add markdown handling for description field
- Add description to create build page
You'll need to re-run migrations and seeds to get this field.
=> Adding a description field

components/ImageUpload/image-upload.component.tsx, components/ImageUpload/image-upload.styles.tsx, components/ImageUpload/index.ts, icons/plus.tsx, package.json, pages/build/create.tsx, yarn.lock
~~the POST currently times out while parsing form~~
Only front-end for now.
=> wip on image upload

components/BuildPage/build-page.component.tsx, components/BuildPage/build-page.styles.tsx, types/index.ts
Not much but a step into the right direction, add a mention in the heading, and the list of builds in the sidebar
=> feat: improve rendering blueprint on a page

components/BuildListLookupStats/build-list-lookup-stats.component.tsx, components/BuildListLookupStats/build-list-lookup-stats.styles.tsx, components/BuildListLookupStats/index.ts, pages/index.tsx, redux/selectors/builds.ts
=> feat: add stats on top of search

.env.example, components/BuildFormPage/build-form-page.component.tsx, components/BuildPage/build-page.component.tsx, db/entities/build.entity.ts, package.json, pages/api/build/[id].ts, pages/api/build/index.ts, utils/upload.ts, yarn.lock
This is not ideal, but a first quick implementation. Still to be done:
- Save into a separate table, alongside width/height. The app needs the image ratio to render a bunch of stuff, plus Next image can/should use width/height.
- Use the image on the home page (needs ratio from above)
- Hopefully avoid saving the image to disk, this is currently done by Formidable
- Clean up typings
- Clean up helper functions
=> feat: first implementation of image upload

components/Header/header.component.tsx, pages/_app.tsx, pages/index.tsx, redux/reducer.ts, redux/reducers/auth.ts, redux/store.ts, types/index.ts
=> feat: handle authenticated user in the front-end

components/BuildFormPage/build-form-page.styles.tsx, components/BuildFormPage/step-1.component.tsx, components/BuildFormPage/step-2.component.tsx
=> feat: let user skip blueprint input

db/repository/build.repository.ts, server/api/build.ts, server/usecase/build.usecase.ts
=> feat: validate build ownership on update

server/api/build.ts, server/usecase/build.usecase.ts
It never worked aside from the first build of the database, oops!
=> fix updating build

redux/selectors/builds.ts
=> fix: restore filtering

db/entities/role.entity.ts, db/entities/user.entity.ts, db/index.ts
=> fix: user roles table implementation

components/BuildPage/build-page.component.tsx, db/repository/user.repository.ts, server/usecase/build.usecase.ts
=> feat: allow editing build as admin

components/BuildFormPage/build-form-page.component.tsx, components/BuildFormPage/step-1.component.tsx, components/BuildFormPage/step-2.component.tsx, db/seeds/data/builds.ts, server/usecase/build.usecase.ts, types/index.ts, utils/blueprint.ts
=> feat: guess marked inputs from blueprint to metadata

components/BuildFormPage/step-1.component.tsx, utils/blueprint-heuristics.ts, utils/blueprint.ts
=> refact: extract heuristics

db/entities/build.entity.ts, pages/index.tsx, server/usecase/build.usecase.ts
closes #144 
Also stops trying to load builds without an image on the home page.
=> fix: saving build without image

components/BuildFormPage/build-form-page.component.tsx, components/BuildFormPage/step-2.component.tsx, components/Button/button.styles.tsx, components/Spinner/index.ts, components/Spinner/spinner.component.tsx, components/Spinner/spinner.styles.tsx
- Add spinner on saving the form
- Redirect to build page after save
closes #155
=> feat: improve feedback on saving

components/ui/BuildSubheader/build-subheader.component.tsx, components/ui/BuildSubheader/build-subheader.styles.tsx, components/ui/BuildSubheader/index.ts, pages-components/BuildPage/build-page.component.tsx, pages-components/BuildPage/build-page.styles.tsx
=> ui: rework build page header including categories

components/form/FormikSelect/formik-select.component.tsx, components/ui/FilterList/filter-list.component.tsx, hooks/useGameStates.tsx, pages-components/BuildFormPage/step-2.component.tsx
=> feat: add icons to game state

hooks/useCategories.tsx, hooks/useGameStates.tsx, pages-components/BuildPage/build-page.component.tsx, pages-components/BuildPage/build-page.styles.tsx
=> ui: style build metadata with icons

components/ui/BuildSubheader/build-subheader.component.tsx, components/ui/BuildSubheader/build-subheader.styles.tsx
=> feat: add game state to build header

pages-components/BuildFormPage/build-form-page.component.tsx
=> Add a null image check for build edit page

components/ui/Header/header.component.tsx, components/ui/UserDropdown/index.ts, components/ui/UserDropdown/user-dropdown.component.tsx, components/ui/UserDropdown/user-dropdown.styles.tsx
=> feat: user dropdown in header

.eslintrc, package.json, pages-components/BuildFormPage/build-form-page.component.tsx, pages/_document.tsx, pages/about.tsx, pages/user/[id].tsx, pages/user/index.tsx, redux/selectors/filters.ts, utils/blueprint.ts
extend eslint config and fix various lint errors
=> style: lint code

components/form/FormikInput/formik-input.component.tsx, components/form/FormikInputWrapper/formik-input-wrapper.component.tsx, components/form/Input/input.component.tsx, pages-components/BuildFormPage/step-1.component.tsx
=> fix: correctly validate a blueprint string

components/ui/BuildCard/build-card.component.tsx, components/ui/BuildCard/build-card.styles.tsx, next.config.js, pages-components/BuildPage/build-page.component.tsx
wip on #195 
This is an initial setup using next/images which caches the image, compresses them. It still needs work to properly configure and serve the correct size.
=> perf: use next-images

hooks/useCategories.tsx, redux/reducers/filters.ts, types/index.ts
=> feat: add refinery category

components/ui/BuildIcon/build-icon.component.tsx, components/ui/BuildIcon/build-icon.styles.tsx, components/ui/BuildIcon/index.ts
=> feat: add build icon component

components/ui/BuildIcon/build-icon.styles.tsx, components/ui/BuildSubheader/build-subheader.component.tsx, components/ui/ItemIcon/item-icon.component.tsx, pages-components/BuildPage/build-page.component.tsx, pages-components/BuildPage/build-page.styles.tsx
=> feat: use build icon for build page title and book items

components/ui/BuildCard/build-card.component.tsx, components/ui/BuildSubheader/build-subheader.component.tsx, components/ui/WithIcons/index.ts, components/ui/WithIcons/with-icons.component.tsx, components/ui/WithIcons/with-icons.styles.tsx
=> feat: parse icons in build name

components/ui/BuildCard/build-card.component.tsx, components/ui/BuildCardList/build-card-list.component.tsx
I'm not a big fan of how it looks right now. I'll be taking another stab at this whole component.
closes #224
=> feat: add icons to build card

components/ui/BuildCard/build-card.component.tsx, components/ui/BuildCard/build-card.styles.tsx, design/helpers/typo.ts
=> ui: redesign build cards

components/pages/BuildFormPage/build-form-page.component.tsx, components/pages/BuildPage/build-page.component.tsx, components/ui/BuildSubheader/build-subheader.component.tsx, db/seeds/data/builds.ts, redux/selectors/builds.ts, server/usecase/build.usecase.ts, types/index.ts
=> feat: prepare multiple game states

db/migrations/1605393678825-initial.ts, server/api/search.ts, server/index.ts
closes #253 
The search response keys are inspired of Meili: https://github.com/meilisearch/meilisearch-js/blob/eed321e4f1f6b170f91fbdfdec6d8e686f9f78d7/src/types.ts#L94
=> feat: basic search api

components/ui/BuildCard/build-card.component.tsx, components/ui/BuildCard/build-card.styles.tsx, components/ui/WithIcons/with-icons.component.tsx, components/ui/WithIcons/with-icons.styles.tsx
=> ui: rework build card

components/pages/BuildFormPage/build-form-page.component.tsx, components/pages/BuildFormPage/step-2.component.tsx, components/pages/BuildPage/build-page.component.tsx, components/ui/BuildSubheader/build-subheader.component.tsx, server/usecase/build.usecase.ts
=> feat: handle multiple game states

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/tabs/details-tab.component.tsx, frontend/pages/[user]/[slug].tsx, frontend/types/index.ts
Still a lot left to reimplement, but wanted a quick version of the page up and running
=> feat: partly reimplement build page on new API

backend/src/FactorioTech.Api/Controllers/BuildController.cs, backend/src/FactorioTech.Api/Controllers/UserController.cs, backend/src/FactorioTech.Api/Extensions/LinkBuilder.cs, backend/src/FactorioTech.Api/Extensions/ViewModelMapper.cs, backend/src/FactorioTech.Api/ViewModels/BuildsQueryParams.cs, backend/src/FactorioTech.Core/Services/BlueprintService.cs, backend/test/FactorioTech.Tests/BlueprintServiceTests.cs
add `GET /users/{username}/builds`
Note that the counts are off and the `next` and `prev` links will currently point to the main builds list api, but this should be good enough to get you started.
=> list a user's builds

frontend/components/pages/UserBuildListPage/index.ts, frontend/components/pages/UserBuildListPage/user-build-list-page.component.tsx, frontend/components/ui/BuildCard/build-card.component.tsx, frontend/components/ui/BuildCardList/build-card-list.component.tsx, frontend/hooks/useDistributeToColumn.tsx, frontend/pages/[user]/builds.tsx, frontend/pages/index.tsx, frontend/redux/reducers/search.ts, frontend/types/index.ts
Nothing fancy, just wanted the page up
=> feat: bootstrap user builds page

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/UserBuildListPage/user-build-list-page.component.tsx, frontend/components/ui/BuildList/build-list.component.tsx, frontend/components/ui/BuildList/build-list.styles.tsx, frontend/components/ui/BuildList/index.ts, frontend/utils/date.ts
=> feat: user builds list

backend/src/FactorioTech.Api/Controllers/BuildController.cs, backend/src/FactorioTech.Api/ViewModels/CreateRequest.cs, backend/src/FactorioTech.Core/Domain/GameIcon.cs, frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/step-1.component.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx, frontend/hooks/useApi.ts, frontend/package.json, frontend/pages/_app.tsx, frontend/yarn.lock
still pretty WIP, missing editing and a lot of hardcoded values still
=> feat: create build with api

frontend/package.json, frontend/pages/_app.tsx, frontend/yarn.lock
@dstockhammer I do not know/have access to the key
=> chore: add monitoring

backend/src/FactorioTech.Core/Services/AssetService.cs, deploy/templates/web/deployment.yaml, deploy/values.yaml, frontend/components/ui/ItemIcon/item-icon.component.tsx, frontend/next.config.js
only icons for now as trial run
=> enable cdn for icons

frontend/components/pages/BuildPage/tabs/blueprints-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx
It's not perfect but feels/looks better
=> feat: build blueprints images

frontend/components/ui/BuildCard/build-card.component.tsx, frontend/components/ui/BuildCard/build-card.styles.tsx
=> ui: tweak build cards

frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/FavoriteButton/favorite-button.component.tsx, frontend/components/ui/FavoriteButton/favorite-button.styles.tsx, frontend/components/ui/FavoriteButton/index.ts
Note the button is purposely not pretty.
=> feat: favorite build

frontend/components/ui/Filter/filter.component.tsx, frontend/components/ui/FilterList/filter-group.component.tsx, frontend/components/ui/FilterList/filter-list.component.tsx, frontend/components/ui/FilterList/filter-list.styles.tsx, frontend/redux/reducers/filters.ts, frontend/redux/reducers/search.ts, frontend/redux/selectors/filters.ts, frontend/types/index.ts
=> feat: bootstrap frontend tags for filtering

frontend/components/pages/BuildPage/build-page.styles.tsx, frontend/components/pages/BuildPage/tabs/blueprint-json-tab.component.tsx, frontend/components/pages/BuildPage/tabs/blueprint-string-tab.component.tsx, frontend/components/pages/BuildPage/tabs/blueprints-tab.component.tsx, frontend/components/pages/BuildPage/tabs/details-tab.component.tsx, frontend/components/pages/BuildPage/tabs/required-items-tab.component.tsx, frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/BuildHeader/build-header.styles.tsx, frontend/components/ui/Button/button.component.tsx, frontend/components/ui/Button/button.styles.tsx, frontend/components/ui/ButtonClipboard/button-clipboard.component.tsx, frontend/components/ui/FavoriteButton/favorite-button.component.tsx, frontend/components/ui/FavoriteButton/favorite-button.styles.tsx
=> ui: iterate build page

frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/Tooltip/index.ts, frontend/components/ui/Tooltip/tooltip.component.tsx, frontend/components/ui/Tooltip/tooltip.styles.tsx
=> feat: tooltips for dates

frontend/components/ui/BuildHeader/build-header.component.tsx
Don't know if there is a value at full ISO? What do you think?
=> feat: switch tooltip dates to human

frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx
Going to improve the UI, but it works and saves
=> feat: add tags in build form

frontend/components/form/ErrorMessage/error-message.component.tsx, frontend/components/form/ErrorMessage/error-message.styles.tsx, frontend/components/form/ErrorMessage/index.ts, frontend/components/form/FormikInput/formik-input.component.tsx, frontend/components/form/FormikInputWrapper/formik-input-wrapper.component.tsx, frontend/components/form/InputWrapper/input-wrapper.component.tsx, frontend/components/form/InputWrapper/input-wrapper.styles.tsx, frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/pager.component.tsx, frontend/components/pages/BuildFormPage/step-2-cover.component.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx
Greatly improve the previously inexistant validation feedback. Cover needs a proper fix.
=> feat: form validation feedback

frontend/components/pages/BuildPage/build-page.styles.tsx, frontend/components/pages/BuildPage/tabs/required-items-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx, frontend/components/ui/BlueprintRequiredItems/blueprint-required-items.component.tsx, frontend/components/ui/BlueprintRequiredItems/blueprint-required-items.styles.tsx, frontend/components/ui/BlueprintRequiredItems/index.ts
=> feat: add required items to blueprint list

frontend/.babelrc, frontend/pages/_document.tsx
=> fix: attempt to fix styled components SSR

frontend/components/pages/UserBuildListPage/user-build-list-page.component.tsx, frontend/components/ui/Avatar/avatar.component.tsx, frontend/components/ui/Avatar/avatar.styles.tsx, frontend/components/ui/Avatar/index.ts, frontend/components/ui/BuildList/build-list.component.tsx, frontend/components/ui/BuildList/build-list.styles.tsx, frontend/components/ui/Tooltip/tooltip.styles.tsx, frontend/components/ui/UserDropdown/user-dropdown.component.tsx, frontend/components/ui/UserDropdown/user-dropdown.styles.tsx, frontend/design/tokens/color.ts
=> ui: revamp build list page

frontend/components/ui/UserDropdown/user-dropdown.component.tsx, frontend/components/ui/UserDropdown/user-dropdown.styles.tsx
=> feat: link to my builds

frontend/components/ui/BuildList/build-list.component.tsx, frontend/components/ui/BuildList/build-list.styles.tsx
=> feat: sort my builds

frontend/components/form/InputGroup/input-group.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx
=> feat: make tags collapsable

frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/ui/Container/container.component.tsx, frontend/components/ui/Container/container.styles.tsx, frontend/components/ui/Layout/layout.component.tsx
=> ui: medium layout for build and form pages

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-cover.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx, frontend/components/ui/Button/button.component.tsx
=> feat: build form pick book render

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/pager.component.tsx
=> ui: restyle build form pager

frontend/components/form/FormikInputWrapper/formik-input-wrapper.component.tsx, frontend/components/form/InputGroup/input-group.component.tsx, frontend/components/form/InputGroup/input-group.styles.tsx, frontend/components/form/InputWrapper/input-wrapper.component.tsx, frontend/components/form/InputWrapper/input-wrapper.styles.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx
=> ui: tweak build form tags styling

frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/step-1.component.tsx
Fixing inconsistencies in the form submit:
- Version.icons is required
- Cover.hash automatically filled
=> fix: make build form submit

frontend/components/form/FormikInput/formik-input.component.tsx, frontend/components/form/FormikInputWrapper/formik-input-wrapper.component.tsx, frontend/components/form/Input/input.component.tsx, frontend/components/form/Input/input.styles.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx
=> feat: add prefix to slug input

frontend/components/form/Checkbox/checkbox.component.tsx, frontend/components/form/Checkbox/checkbox.styles.tsx, frontend/components/form/FormikCheckbox/formik-checkbox.component.tsx, frontend/components/form/Input/input.styles.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/pager.component.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx, frontend/package.json, frontend/yarn.lock
Greatly improves the accessibility of the form, keyboard navigable, visual focus etc.
=> ui: improve build form a11y

frontend/components/ui/BuildCard/build-card.component.tsx, frontend/components/ui/BuildCard/build-card.styles.tsx
Cards are now keyboard navigable.
=> feat(a11y): build cards

frontend/components/ui/BuildListSort/build-list-sort.component.tsx
Make build list keyboard navigable.
=> feat(a11y): sort by

frontend/components/pages/BuildFormPage/step-1.component.tsx, frontend/utils/blueprint-heuristics.ts
First iteration to parse the majority of tags that were easy to parse, excluding production tags.
=> feat: parse blueprint tags

frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/icons/editor.tsx, frontend/icons/raw.tsx
(all of) the icons needs balanced, but it's a (bigger) task for another PR
=> ui: add icons to build page buttons

frontend/components/ui/Header/header.component.tsx, frontend/components/ui/Header/header.styles.tsx, frontend/components/ui/Layout/layout.component.tsx, frontend/components/ui/Layout/layout.styles.tsx, frontend/components/ui/Sidebar/sidebar.styles.tsx, frontend/design/styles/global-style.ts, frontend/design/styles/media.ts, frontend/icons/burger.tsx, frontend/package.json, frontend/pages/_app.tsx, frontend/pages/_document.tsx, frontend/redux/reducer.ts, frontend/redux/reducers/layout.ts, frontend/redux/store.ts, frontend/yarn.lock
=> ui: make homepage mobile friendly

frontend/components/form/Input/input.component.tsx, frontend/components/ui/Header/header.component.tsx, frontend/components/ui/Header/header.styles.tsx, frontend/components/ui/Search/search.component.tsx, frontend/components/ui/Sidebar/sidebar.component.tsx, frontend/components/ui/Sidebar/sidebar.styles.tsx, frontend/pages/_document.tsx
Not that it's a huge benchmark, but going from 74 to 91 accessibility on Lighthouse
=> feat: a11y pass

frontend/components/form/Checkbox/checkbox.styles.tsx, frontend/components/form/Input/input.styles.tsx, frontend/components/pages/BuildListPage/build-list-page.component.tsx, frontend/components/ui/BuildCardList/build-card-list.component.tsx, frontend/components/ui/BuildCardList/build-card-list.styles.tsx, frontend/components/ui/BuildListLookupStats/build-list-lookup-stats.component.tsx, frontend/components/ui/BuildListLookupStats/build-list-lookup-stats.styles.tsx, frontend/components/ui/BuildListSort/build-list-sort.component.tsx, frontend/components/ui/BuildListSort/build-list-sort.styles.tsx, frontend/components/ui/Filter/filter.component.tsx, frontend/components/ui/FilterList/filter-group.component.tsx, frontend/components/ui/FilterList/filter-list.styles.tsx, frontend/components/ui/Layout/layout.styles.tsx, frontend/components/ui/Search/search.styles.tsx, frontend/components/ui/Sidebar/sidebar.styles.tsx, frontend/icons/caret.tsx, frontend/pages/index.tsx, frontend/redux/reducers/search.ts, frontend/types/index.ts
work on #452. Missing hover effects on filter checkboxes & filer group count.
=> ui: rework homepage

frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/utils/date.ts
=> feat: inverse date tooltip

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/build-page.styles.tsx, frontend/components/pages/BuildPage/tabs/image-mobile-tab.component.tsx, frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/BuildHeader/build-header.styles.tsx, frontend/components/ui/Button/button.styles.tsx
Not perfect but much better than what it was
=> ui: mobile friendly build page

frontend/components/form/Checkbox/checkbox.styles.tsx, frontend/components/ui/FilterList/filter-group.component.tsx
=> ui: hover styles for filters/checkboxes

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx, frontend/components/pages/BuildFormPage/useCanSave.ts
=> feat: add feedback for the user as bp is rendering

frontend/components/ui/Filter/filter.component.tsx, frontend/components/ui/FilterList/filter-group.component.tsx, frontend/components/ui/FilterList/filter-list.styles.tsx
=> feat: add count to filter list

frontend/components/pages/BuildPage/tabs/required-items-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintRequiredItems/blueprint-required-items.component.tsx
=> feat: add tiles to blueprint item

frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx
=> feat: add loading indicator to images

frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/build-page.styles.tsx
=> feat: allow zooming in on build image

frontend/components/ui/Links/links.component.tsx, frontend/components/ui/Links/links.styles.tsx, frontend/icons/line.tsx
=> feat: add link to about page

frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildPage/build-page.component.tsx, frontend/components/pages/BuildPage/build-page.styles.tsx, frontend/components/pages/UserBuildListPage/user-build-list-page.component.tsx, frontend/components/ui/BuildCardList/build-card-list.styles.tsx, frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/BuildHeader/build-header.styles.tsx, frontend/components/ui/BuildList/build-list.styles.tsx, frontend/components/ui/Layout/layout.component.tsx, frontend/components/ui/Layout/layout.styles.tsx
=> ui: rework build page

frontend/components/ui/BuildHeader/build-header.styles.tsx
=> ui: tweak build tags styles

frontend/components/ui/BuildHeader/build-header.component.tsx, frontend/components/ui/Button/button.component.tsx, frontend/components/ui/Button/button.styles.tsx
=> feat: make raw and fbe buttons links

frontend/components/ui/UserDropdown/user-dropdown.component.tsx, frontend/components/ui/UserDropdown/user-dropdown.styles.tsx, frontend/pages/_app.tsx
=> ui: redesign user dropdown + make it accessible

frontend/components/ui/Links/links.component.tsx
=> feat(a11y): make about link focusable

frontend/components/form/FormikInput/formik-input.component.tsx, frontend/components/form/FormikInputWrapper/formik-input-wrapper.component.tsx, frontend/components/form/Input/input.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx
=> feat: make slug uneditable

backend/src/FactorioTech.Api/Controllers/BuildController.cs, backend/src/FactorioTech.Api/Controllers/PayloadController.cs, backend/src/FactorioTech.Api/Controllers/RpcController.cs, backend/src/FactorioTech.Api/Controllers/UserController.cs, backend/src/FactorioTech.Core/Services/FbsrClient.cs, backend/src/FactorioTech.Core/Services/ImageService.cs
... and add more logging to the rendering flow in general
=> fix not accepted result on 404 rendering

frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx
This is a simple implementation to at least support zooming. Not perfect but better than nothing.
wip on #466
=> feat: zoom on blueprint item

frontend/components/pages/BuildPage/tabs/blueprints-tab.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.component.tsx, frontend/components/ui/BlueprintItem/blueprint-item.styles.tsx
=> feat: add raw and copy button to bp item

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-2-data.component.tsx, frontend/icons/caret.tsx
=> ui: tweak build form tags

.github/workflows/analyze-build-size.yml, frontend/package.json, frontend/scripts/bundle-size.js
mostly taken from https://jeffchen.dev/posts/Measuring-Bundle-Sizes-With-Next-js-And-Github-Actions/
=> build: add bundle size to gh actions

frontend/components/pages/BuildFormPage/build-form-page.d.tsx, frontend/components/pages/BuildFormPage/build-form-page.helpers.ts, frontend/components/pages/BuildFormPage/validation.ts
=> fix: solve editing a blueprint with a custom image

frontend/next.config.js
See https://nextjs.org/docs/messages/webpack5 for context
=> chore: switch to webpack 5

frontend/components/form/FormError/form-error.component.tsx, frontend/components/form/FormError/form-error.styles.tsx, frontend/components/form/FormError/index.ts, frontend/components/pages/BuildFormPage/build-form-page.component.tsx, frontend/components/pages/BuildFormPage/build-form-page.d.tsx, frontend/components/pages/BuildFormPage/build-form-page.styles.tsx, frontend/components/pages/BuildFormPage/step-1.component.tsx, frontend/components/pages/BuildFormPage/step-2.component.tsx
This is a first step on #517, not perfect but at least provides basic feedback when either step of the form fails to submit.
=> feat: add basic error on build creation

frontend/components/pages/BuildFormPage/step-2-data.component.tsx
=> feat: show preview of rich text inside build form

frontend/components/ui/UserDropdown/user-dropdown.component.tsx, frontend/pages/_app.tsx, frontend/utils/auth.ts
=> fix: clear token on logout

frontend/components/pages/BuildPage/tabs.component.tsx, frontend/components/ui/Header/header.component.tsx, frontend/components/ui/LayoutSidebar/layout-sidebar.component.tsx, frontend/components/ui/UserDropdown/user-dropdown.component.tsx, frontend/design/helpers/media.tsx
This massively improves readability of templates, and abstract the awkward usage of the Media component necessary for SSR.
=> refact: clean up desktop and mobile helpers

frontend/components/ui/BuildCard/build-card.component.tsx
Basic implementation of just the homepage for now.
Next up:
- All of the images
- A more advanced implementation
=> perf: use optimized images on homepage

frontend/components/ui/BuildImage/build-image.component.tsx
oops, this was causing hundred of console errors
=> fix: invalid srcSet on image

frontend/components/pages/BuildFormPage/build-form-page.styles.tsx
=> ui: limit selected rendering width

frontend/package.json, frontend/yarn.lock
Main bundle from 147.31KB to 113.29KB.
Build page bundle from 404.37KB to 370.98KB.
Pretty substantial reduction in size.
=> chore: bump deps
